### ISSUE TITLE
Error in Firefox Ubuntu

### ISSUE THREAD

**Issue by berndca** [librecores/librecores-web#127] opened 2017-02-11 00:13 UTC
There appears to be a problem with the google analytic.js. I get an error in Firefox 51.01 (Ubuntu):

`SyntaxError: function statement requires a name  analytics.js:1:436`

Here is a screenshot.
![librecores-analytics](https://cloud.githubusercontent.com/assets/466654/22848786/c0da6f62-efab-11e6-9c9f-c0754ec972f6.png)

It looks fine in Chrome.

**Comment by imphil** [comment] 2017-02-12 11:06
Looks like either Firefox is broken or your internet connection during this page load. analytics.js is provided by Google, it's highly unlikely they'll ship a non-working version to billions of people. (And if they did, I'm sure it would be resolved by now.)

Please reopen if this is reproducible on your side.

**Closed by imphil** 2017-02-12 11:06 UTC

**Comment by berndca** [comment] 2017-02-13 12:10
The cause appears to be the interaction of the NoScript Firefox addon trying to block google-analytics and the analytics script. The strange thing is that this setup had been working fine for the last few weeks.
