### ISSUE TITLE
Sign in with Google Account gives 401 Error

### ISSUE THREAD

**Issue by menikhilpandey** [librecores/librecores-web#136] opened 2017-04-09 18:18 UTC
Signing in by using Google account gives 401 Error stating that "The OAuth client was deleted."
![screenshot from 2017-04-09 23 46 54](https://cloud.githubusercontent.com/assets/16885925/24839818/11b412e8-1d7f-11e7-9959-acb41f5cce50.png)

**Comment by imphil** [comment] 2017-04-10 21:59
This is most likely caused by a deployment issue (master is not yet deployed to production). It will be fixed hopefully with the next deployment to production.

**Comment by imphil** [comment] 2017-04-10 23:45
This should now be fixed in production, please give a try. Please re-open if it doesn't work for you.

**Closed by imphil** 2017-04-10 23:45 UTC
